// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4mypNuUbx4i9U8-wSgDwapqw-qz7u4Wo',
    appId: '1:328588951703:web:625d7841acab3ebb5669d2',
    messagingSenderId: '328588951703',
    projectId: 'mon-coiffeur-3c71f',
    authDomain: 'mon-coiffeur-3c71f.firebaseapp.com',
    storageBucket: 'mon-coiffeur-3c71f.firebasestorage.app',
    measurementId: 'G-PMRPR7MH1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRUFSNb7Mz76moz0OQ9alz1ouJeYZEkWk',
    appId: '1:328588951703:android:34145c10831834f85669d2',
    messagingSenderId: '328588951703',
    projectId: 'mon-coiffeur-3c71f',
    storageBucket: 'mon-coiffeur-3c71f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCknK97DsUQEiLGB10fgr92oYFRa7w4XyQ',
    appId: '1:328588951703:ios:364195721038860b5669d2',
    messagingSenderId: '328588951703',
    projectId: 'mon-coiffeur-3c71f',
    storageBucket: 'mon-coiffeur-3c71f.firebasestorage.app',
    iosBundleId: 'com.example.monApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCknK97DsUQEiLGB10fgr92oYFRa7w4XyQ',
    appId: '1:328588951703:ios:364195721038860b5669d2',
    messagingSenderId: '328588951703',
    projectId: 'mon-coiffeur-3c71f',
    storageBucket: 'mon-coiffeur-3c71f.firebasestorage.app',
    iosBundleId: 'com.example.monApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4mypNuUbx4i9U8-wSgDwapqw-qz7u4Wo',
    appId: '1:328588951703:web:4fa33c33e034962e5669d2',
    messagingSenderId: '328588951703',
    projectId: 'mon-coiffeur-3c71f',
    authDomain: 'mon-coiffeur-3c71f.firebaseapp.com',
    storageBucket: 'mon-coiffeur-3c71f.firebasestorage.app',
    measurementId: 'G-WEDH5LS63C',
  );
}
